spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/orderdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: INFO
    com.aliev.mes: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{traceId}] %logger{36}: %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health, info
