spring:
  application:
    name: receiving-order-service
  config:
    import: "configuration-service:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: configuration-service
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/